### ISSUE TITLE
Ensure Compatibility of Pillow Dependencies with NVDA 2024.1

### ISSUE THREAD

**Issue by cary-rowen** [huaiyinfeilong/xyOCR#1]
## Summary

NVDA2024.1 is built using Python 3.11. The Pillow dependency used by this add-on needs to be updated to be compatible with Python 3.11.

## Request

If you'd like, I'd be happy to update this dependency for easy compatibility with NVDA2024.1.

**Comment by Neurrone** [comment]
I'd love to be able to use this with NVDA 2024.1 as well.

**Comment by cary-rowen** [comment]
Done
